CREATE DATABASE CRUD_POST_4A;
USE CRUD_POST_4A;

CREATE TABLE POSTS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
